apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bar
  janus-idp.io/tekton: bar
  backstage.io/kubernetes-id: bar
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bar
resources:
- deployment.yaml
- route.yaml
- service.yaml
