apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: bar
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bar 
  name: bar
spec:
  port:
    targetPort: 8080 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: bar
    weight: 100 
