apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bar
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bar 
  name: bar
spec:
  ports:
  - port: 8080 
    targetPort: 8080 
  selector:
    app.kubernetes.io/instance: bar 
